name = "DecisionStructures"
uuid = "898d3975-6f61-4afe-9cf3-db6863983db4"
authors = ["Carl Julius Martensen"]
version = "0.0.1"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
AbstractTrees = "0.4"
DocStringExtensions = "0.9"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
